language: minimal
dist: xenial
before_install:
  - curl https://dl.google.com/go/go1.12.1.linux-amd64.tar.gz --output /tmp/go1.12.1.linux-amd64.tar.gz
  - sudo tar -C /usr/local -zxf /tmp/go1.12.1.linux-amd64.tar.gz
  - ls -lah
  - pwd

env:
  global:
    GO111MODULE: "on"

script:
  - export GOROOT=/usr/local/go
  - export GOPATH=$HOME/go
  - export PATH=$GOROOT/bin:$GOPATH/bin:$PATH
  - go version
  - go test -v ./...
